# Generated by Django 4.2.1 on 2023-07-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('technology', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(max_length=80, verbose_name='Marca vehículo')),
                ('modelo', models.CharField(blank=True, max_length=80, null=True, verbose_name='Modelo')),
                ('imagen', models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen')),
                ('servicio', models.CharField(choices=[('suspension_direccion', 'Suspension y Direccion'), ('cajas_cambio', 'Cajas de Cambio'), ('electronica_automotriz', 'Electronica Automotriz')], max_length=40, verbose_name='servicio')),
                ('detalle_servicio', models.CharField(max_length=200, verbose_name='detalle servicio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
    ]
